image: microsoft/dotnet:2.2-sdk 
stages:
  # - build
  # - test
  # - publish
  - build-test-publish

build-test-publish:
  stage: build-test-publish
  script:
    - ./etc/build/gitversion.sh
    - dotnet build example.serialisation.sln
    - curl -s https://codecov.io/bash > codecov
    - chmod +x codecov
    - dotnet test example.serialisation.core.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - ./codecov -f example.serialisation.core.tests/coverage.opencover.xml -t $CODECOV_TOKEN
    - dotnet test example.serialisation.json.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - ./codecov -f example.serialisation.json.tests/coverage.opencover.xml -t $CODECOV_TOKEN
    - dotnet test example.serialisation.binary.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
    - ./codecov -f example.serialisation.binary.tests/coverage.opencover.xml -t $CODECOV_TOKEN
    - dotnet pack example.serialisation -o $CI_PROJECT_DIR/nupkgs
    - dotnet nuget push $CI_PROJECT_DIR/nupkgs/* -k $MYGET_APIKEY -s $MYGET_URL

# build:
#   stage: build
#   script:
#     - ./etc/build/gitversion.sh
#     - dotnet build example.serialisation.sln

# test:
#   stage: test
#   script:
#     - ./etc/build/gitversion.sh
#     - curl -s https://codecov.io/bash > codecov
#     - chmod +x codecov
#     - dotnet test example.serialisation.core.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
#     - ./codecov -f example.serialisation.core.tests/coverage.opencover.xml -t $CODECOV_TOKEN
#     - dotnet test example.serialisation.json.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
#     - ./codecov -f example.serialisation.json.tests/coverage.opencover.xml -t $CODECOV_TOKEN
#     - dotnet test example.serialisation.binary.tests /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
#     - ./codecov -f example.serialisation.binary.tests/coverage.opencover.xml -t $CODECOV_TOKEN

# publish:
#   stage: publish
#   script:    
#     - ./etc/build/gitversion.sh
#     - dotnet pack example.serialisation -o /tmp/nupkgs
#     - dotnet nuget push /tmp/nupkgs/* -k $MYGET_APIKEY -s $MYGET_URL
